Set ESLint parser options to 'script'
We may have misunderstood the ESLint docs but 'commonjs' seemed the appropriate sourceType to set.

> commonjs - CommonJS module (useful if your code uses require()). Your code has a top-level function scope and runs in non-strict mode.

Running the linting worked fine. But then we tried to run the unit tests

```
> water-abstraction-system@0.18.0 test
> lab --silent-skips --shuffle

Error requiring file: /home/repos/water-abstraction-system/test/controllers/bill-licences.controller.test.js
.sourceType must be "module", "script", "unambiguous", or undefined
Error: .sourceType must be "module", "script", "unambiguous", or undefined
    at validate (/home/repos/water-abstraction-system/node_modules/@babel/core/lib/config/validation/options.js:92:25)
    at loadPrivatePartialConfig (/home/repos/water-abstraction-system/node_modules/@babel/core/lib/config/partial.js:80:50)
    at loadPrivatePartialConfig.next (<anonymous>)
    at Object.<anonymous> (/home/repos/water-abstraction-system/node_modules/@babel/core/lib/config/partial.js:149:25)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/repos/water-abstraction-system/node_modules/gensync/index.js:251:28)
    at Object.sync [as loadPartialConfigSync] (/home/repos/water-abstraction-system/node_modules/gensync/index.js:89:14)
    at normalizeBabelParseConfigSync (/home/repos/water-abstraction-system/node_modules/@babel/eslint-parser/lib/worker/configuration.cjs:87:24)
    at LocalClient.handleMessage (/home/repos/water-abstraction-system/node_modules/@babel/eslint-parser/lib/worker/handle-message.cjs:25:90)
    at LocalClient.<anonymous> (/home/repos/water-abstraction-system/node_modules/@babel/eslint-parser/lib/client.cjs:98:79)
    at LocalClient.maybeParse (/home/repos/water-abstraction-system/node_modules/@babel/eslint-parser/lib/client.cjs:52:47)
    at parse (/home/repos/water-abstraction-system/node_modules/@babel/eslint-parser/lib/parse.cjs:28:14)
    at Object.parse (/home/repos/water-abstraction-system/node_modules/@babel/eslint-parser/lib/index.cjs:19:10)
    at internals.instrument (/home/repos/water-abstraction-system/node_modules/@hapi/lab/lib/modules/coverage.js:327:31)
    at require.extensions.<computed> [as .js] (/home/repos/water-abstraction-system/node_modules/@hapi/lab/lib/modules/coverage.js:117:59)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/repos/water-abstraction-system/test/controllers/bill-licences.controller.test.js:12:34)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at require.extensions.<computed> [as .js] (/home/repos/water-abstraction-system/node_modules/@hapi/lab/lib/modules/coverage.js:123:28)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at internals.tryToResolveCJS (/home/repos/water-abstraction-system/node_modules/mo-walk/lib/index.js:144:17)
    at exports.tryToResolve (/home/repos/water-abstraction-system/node_modules/mo-walk/lib/index.js:106:22)
    at internals.traverse (/home/repos/water-abstraction-system/node_modules/@hapi/lab/lib/cli.js:152:39)
    at async exports.run (/home/repos/water-abstraction-system/node_modules/@hapi/lab/lib/cli.js:61:21)
    at async main (/home/repos/water-abstraction-system/node_modules/@hapi/lab/bin/lab:56:22)
```

We suspect this is an issue with Hapi Lab and its dependencies (boy we love JavaScript!) Setting the sourceType to 'script' makes the tests happy and we ESLint is still doing what we want it to.