Fix logging of unhandled errors (#352)
https://eaflood.atlassian.net/browse/WATER-4083

Whilst investigating an issue with an erroring SROC Supplementary bill run we observed that when the error is logged the stack trace we get isn't beneficial.

To replicate this, we altered the `InfoService` which is called by the controller on `/health/info` with this

```javascript
async function go () {
  const boomBoom = undefined
  console.log(boomBoom.boom)

  // ...
}
```

Hitting the endpoint then causes an unhandled exception to be thrown. As expected, the user is redirected to our error page. But this is what we get for the log message.

```
[08:23:49.494] ERROR (6202): Cannot read properties of undefined (reading 'boom')
statusCode: 500
stack: "TypeError: Cannot read properties of undefined (reading 'boom')\n    at Object.go (/home/repos/water-abstraction-system/app/services/health/info.service.js:28:24)\n    at index (/home/repos/water-abstraction-system/app/controllers/health/info.controller.js:11:38)\n    at exports.Manager.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/toolkit.js:57:29)\n    at Object.internals.handler (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:46:48)\n    at exports.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:31:36)\n    at Request._lifecycle (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:370:68)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Request._execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:280:9)"
req: {
  "id": "1692001429489:852a235f4312:6202:llalyie0:10000"
}
err: {
  "type": "Error",
  "message": "Cannot read properties of undefined (reading 'boom')",
  "stack":
      Error: Cannot read properties of undefined (reading 'boom')
          at RequestNotifierLib.omfg (/home/repos/water-abstraction-system/app/lib/base-notifier.lib.js:92:15)
          at /home/repos/water-abstraction-system/app/plugins/error-pages.plugin.js:37:32
          at exports.Manager.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
          at Request._invoke (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:397:55)
          at Request._postCycle (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:468:86)
          at Request._reply (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:447:20)
          at Request._execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:281:14)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
}
```

As you can see, `InfoService` is not mentioned anywhere. This makes it hard to track down exactly where an issue arose. This change fixes the error logging to ensure the stack trace points to where the error occurred, as in this example

```
[08:44:50.463] ERROR (6238): Cannot read properties of undefined (reading 'boom')
    req: {
      "id": "1692002690453:852a235f4312:6238:llamjgdj:10000"
    }
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'boom')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'boom')
              at Object.go (/home/repos/water-abstraction-system/app/services/health/info.service.js:28:24)
              at index (/home/repos/water-abstraction-system/app/controllers/health/info.controller.js:11:38)
              at exports.Manager.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
              at Object.internals.handler (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:46:48)
              at exports.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:31:36)
              at Request._lifecycle (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:370:68)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async Request._execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:280:9)
      "isBoom": true,
      "isServer": true,
      "data": null,
      "output": {
        "statusCode": 500,
        "payload": {
          "statusCode": 500,
          "error": "Internal Server Error",
          "message": "An internal server error occurred"
        },
        "headers": {}
      },
      "isDeveloperError": true
    }
```

------

When implementing this we took the opportunity to refactor the logic in the error pages plugin into its own service. It keeps the plugin simple and makes for easier testing.

It isn't a direct copy and paste because we learnt some things whilst testing the error handling.

- if it's an unhandled error, one that has been manually boomified or a 404, `response` will always we be a boom error. There is no point in trying to handle a situation where this is not the case
- we could stick with putting the `plainOutput:` option on a route's `options.settings.plugins` property. But as we are already using `options.settings.app` for custom config (see route filtering) it made sense to also use it for this

We also always want to log anything that is a 404, and send an airbrake notification for any other boom error so made the service take care of that.

After updating the config on the `/bill-runs` route we knew we had more than it which should be treated as API-only. So, we took this opportunity to search them out and apply the config flag.

Finally, when we ran the test suite we spotted this for the output of the `DataController`.

```
Data controller
  GET /data/export
    when the request succeeds
      ✔ 375) displays the correct message (1 ms)
  POST /data/seed
    when the request succeeds
      ✔ 376) displays the correct message (1 ms)
Debug: internal, implementation, error
    Error: Error
    at seed (/home/repos/water-abstraction-system/app/controllers/data/data.controller.js:31:124)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.Manager.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at async Object.internals.handler (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at async Request._lifecycle (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:370:32)
    at async Request._execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:280:9)
    when the request fails
      because the SeedService errors
        ✔ 377) returns a 500 status (2 ms)
  POST /data/tear-down
    when the request succeeds
      ✔ 378) returns a 204 status (3 ms)
Debug: internal, implementation, error
    Error: Error
    at tearDown (/home/repos/water-abstraction-system/app/controllers/data/data.controller.js:41:124)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.Manager.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at async Object.internals.handler (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at async Request._lifecycle (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:370:32)
    at async Request._execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:280:9)
    when the request fails
      because the TearDownService errors
        ✔ 379) returns a 500 status (4 ms)
```

Because we are catching errors and then re-making them as boom errors it means we are getting the unwanted logging output. But it also means we are losing the details on the thrown error including the stack trace. As this change was initiated to fix the `ErrorPagesPlugin` to prevent just that we took the opportunity to fix the error handling in the `DataController` as well.