Fixed version of Jest investigation branch
https://eaflood.atlassian.net/browse/WATER-4144

At time of writing we are investigating 2 issues in our **Investigate switching to jest** PR.

The first of these is that locally Jest does not exit when the test suite finishes any more. When pushed to GitHub CI does complete successfully, but the unit tests clock in at 1 hour to complete. We can see it is the same issue.

The second is that we see the following in the test output

```
console.error
    Debug: internal, implementation, error
        Error: Cannot throw non-error object
        at Object.<anonymous>.exports.Manager.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/toolkit.js:67:33)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at Object.<anonymous>.internals.handler (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:46:20)
        at Object.<anonymous>.exports.execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/handler.js:31:20)
        at Request._lifecycle (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:370:32)
        at Request._execute (/home/repos/water-abstraction-system/node_modules/@hapi/hapi/lib/request.js:280:9)

      at method (node_modules/@hapi/hapi/lib/core.js:151:21)
      at Object.listener (node_modules/@hapi/hapi/lib/core.js:161:77)
      at Object.<anonymous>.exports.Podium.#emitToEachListener (node_modules/@hapi/hapi/node_modules/@hapi/podium/lib/index.js:204:39)
      at Object.<anonymous>.exports.Podium.emit (node_modules/@hapi/hapi/node_modules/@hapi/podium/lib/index.js:91:33)
      at Request._log (node_modules/@hapi/hapi/lib/request.js:608:27)
      at Request._finalize (node_modules/@hapi/hapi/lib/request.js:501:22)
      at Request._reply (node_modules/@hapi/hapi/lib/request.js:457:14)
```

All the tests pass at the end but obviously this isn't ideal. This branch is about investigating and hopefully solving these issues.