Import Joi from water-abstraction-engine
https://eaflood.atlassian.net/browse/WATER-5744

When we [created the engine](https://github.com/DEFRA/water-abstraction-engine/commit/db764fb896c8c5ecccb3e4da1a0c25f010053a14), one of the things we needed to implement was 'wrappers'. Our apps share a number of the same dependencies, with **Hapi** being the obvious one.

Most of these shared dependencies are only referenced in the engine code, so no special treatment is needed. But if an app depends on a shared dependency, for example, [Objection](https://vincit.github.io/objection.js/), then we need to 'wrap' the dependency so we can make it available from the engine.

Because of how Node.js and NPM work, the only alternative is to list the dependency in all three places, which we want to avoid.

We've spotted an issue when running unit tests after running `npm link` and working locally. Many tests fail with the following:

```text
 FAIL   series  test/services/return-versions/setup/submit-start-date.service.test.js [ test/services/return-versions/setup/submit-start-date.service.test.js ]
Error: Cannot find package 'joi' imported from /home/repos/water-abstraction-system/src/validators/return-versions/setup/start-date.validator.js
 ❯ src/validators/return-versions/setup/start-date.validator.js:6:1
      4|  */
      5|
      6| import base from 'joi'
       | ^
      7| import joiDate from '@joi/date'
      8| import { leftPadZeroes } from 'water-abstraction-engine/presenters/base.presenter.js'
 ❯ src/services/return-versions/setup/submit-start-date.service.js:13:1
```

It is because we've overlooked that **internal** directly requires [Joi](https://joi.dev/), even though it's not a direct dependency. When the engine has been installed, then it and **Joi** sit inside the engine's `node_modules` folder and everything works fine. But when we run unit tests in **internal** with `npm link`, the engine is 'hoisted', and a symlink exists instead. Anything referenced from the engine still works. But now 'Joi' is no longer in the app's `node_modules`, so it **internal** errors when loading those modules.

In this change, we update references to **Joi** to use the engine wrapper instead.